/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package audio_authentication_system;

import java.util.ArrayList;

/**
 *
 * @author acer
 */
public class Login extends javax.swing.JFrame {
    
    private long time1;
    private long time2;
    private ArrayList<String> keytime= new ArrayList<String>();
   // private long time3;
  //  private long time4;
   //// private ArrayList<String> keytime1= new ArrayList<String>();
  //  private long time5;
   // private long time6;
   // private ArrayList<String> keytime2= new ArrayList<String>();
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        userNa = new java.awt.TextField();
        passWo = new java.awt.TextField();
        authenticate = new java.awt.Button();
        label5 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(204, 204, 204));
        label1.setFont(new java.awt.Font("DigifaceWide", 3, 24)); // NOI18N
        label1.setText("Enter Your User Name & Password");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(204, 204, 204));
        label2.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        label2.setText("User Name");

        userNa.setBackground(new java.awt.Color(204, 204, 204));
        userNa.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        userNa.setName(""); // NOI18N
        userNa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNaActionPerformed(evt);
            }
        });
        userNa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNaKeyPressed(evt);
            }
        });

        passWo.setBackground(new java.awt.Color(204, 204, 204));
        passWo.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        passWo.setName(""); // NOI18N
        passWo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWoActionPerformed(evt);
            }
        });
        passWo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passWoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passWoKeyReleased(evt);
            }
        });

        authenticate.setBackground(new java.awt.Color(204, 204, 204));
        authenticate.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        authenticate.setLabel("Authenticate");
        authenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authenticateActionPerformed(evt);
            }
        });

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(new java.awt.Color(204, 204, 204));
        label5.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        label5.setText("Password Attemp1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passWo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(authenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passWo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(authenticate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
  private boolean authenticate(ArrayList<String> key){
      boolean a= false;
      System.out.println("");
      for(int i=0;i<Main_module_Container.users.size();i++){
          if ( Main_module_Container.users.get(i).getName().equals(userNa.getText())  & 
               Main_module_Container.users.get(i).getPassword().equals(passWo.getText()) ) {
              a=true;
              
              for(int j=1;j<Main_module_Container.users.get(i).getKeypressedtime().size();j++){
                int temp=Integer.parseInt(Main_module_Container.users.get(i).getKeypressedtime().get(j));
                //System.out.println(Integer.parseInt(keytime.get(j)));
                ////System.out.println((temp));
               // System.out.println(Math.abs(temp-Integer.parseInt(keytime.get(j))));
               // System.out.println(Main_module_Container.users.get(i).getKeypressedtime().get(j));
                  if (Math.abs(temp-Integer.parseInt(keytime.get(j)))>35){
                      a=false;
                      System.out.println("PAASSWORD ENTER TIME DIFFERENT");
                      //break;
                  }
                  else{
                     System.out.println("time right");
                          }   
              }
              break;
          }
      }
      
      return a;
  }
    //    
      //  System.out.println(Main_module_Container.users.size());
      //  
            // if ( Main_module_Container.users.get(i).getName().equals()
               //  a= true;
                // for(int j=1;i<=Main_module_Container.users.get(i).getKeypressedtime().size();j++){
                     //if( (Math.abs(key.get(j)-Main_module_Container.users.get(i).getKeypressedtime().get(j))/Main_module_Container.users.get(i).getKeypressedtime().get(j))<=0.15 ){
                        // a=false;
                    // }
                    // else{
                        // a=false;
                     //}
              ///   }
            // }
       
         
    
    
    private void userNaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_userNaActionPerformed

    private void passWoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passWoActionPerformed

    private void authenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authenticateActionPerformed
        // TODO add your handling code here:
        if (authenticate(keytime)){
            new Grant().setVisible(true);
            this.dispose();
        }
        else{
            this.dispose();;
            new NotGrant().setVisible(true);        }
    }//GEN-LAST:event_authenticateActionPerformed

    private void passWoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWoKeyPressed
        time1=System.currentTimeMillis();
    }//GEN-LAST:event_passWoKeyPressed

    private void passWoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWoKeyReleased
        time2=System.currentTimeMillis();
        this.keytime.add(""+(time2-time1));
        System.out.print(time2-time1+" ");
        
        
    }//GEN-LAST:event_passWoKeyReleased

    private void userNaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNaKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button authenticate;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label5;
    private java.awt.TextField passWo;
    private java.awt.TextField userNa;
    // End of variables declaration//GEN-END:variables
}
